db:
  name: wpdatabase
  labels:
    id: c0929252
    app: dbapp
    env: dev
  image:
    repository: mariadb
    tag: 10.6.4-focal
    pullPolicy: IfNotPresent
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: c0929252
    MYSQL_USER: 3324_user
    APP_ENV: dev
  containerPorts:
      mysql: 3306
  # volume:
  #     name: nginx-proxy-cache-store
  #     mount:
  #         path: /var/lib/mysql
  #         name: nginx-proxy-cache-store
  #     storage: 1T
  #     nfs:
  #         path: /shared_volume
  #         server: dev-cache-filestore.internal.gdev.postmedia.digital
  #     claim:
  #         name: nginx-proxy-cache-store-claim
